version: 1.0.0.{build}
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2019
configuration:
- Debug
- Release
platform: x64
build:
  project: Hangman.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: 7z a hangman-%CONFIGURATION%.zip words.txt
- cmd: 7z a hangman-%CONFIGURATION%.zip .\%PLATFORM%\%CONFIGURATION%\Hangman.exe
test: off
artifacts:
- path: '**\*.zip'
  name: executable-$(configuration)
deploy:
- provider: GitHub
  tag: hangman-v$(appveyor_build_version)
  auth_token:
    secure: SYXtRdG+3FpTZcSKWje5OmvtUU5rH4+wWloHdBkZJbpY/w8XAQUZK2Y/lzVt6kCD
  artifact: /.*\.zip/
  on:
    branch: master
notifications:
- provider: Email
  to:
  - a.mrukwa00@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
